# https://github.com/benchmark-action/github-action-benchmark#how-to-use
# Do not run this workflow on pull request since this workflow has permission to modify contents.
name: benchmark

on:
  push:
    branches:
      - master

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  benchmark:
    name: Performance regression check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run benchmark
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.dev.txt
          python -m pip install -r requirements.txt
      - name: Test with pytest
        run: |
          coverage run -m pytest --benchmark-json benchmark.json -m benchmark

      # gh-pages branch is updated and pushed automatically with extracted benchmark data
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'pytest'
          output-file-path: benchmark.json
          # Access token to deploy GitHub Pages branch
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Push and deploy GitHub pages branch automatically
          auto-push: true
